version: '3'

services:
  app:
    image: golang:1.20-alpine
    # 初回起動時はDBが接続可能になるまで数秒かかる
    command: go run ./
    environment:
      - DB_PATH=db:3306
    working_dir: /go/src/github.com/kappa-lab/docker-compose-mysql/
    volumes: 
      - ./:/go/src/github.com/kappa-lab/docker-compose-mysql/
    